name: native_workmanager
description: "Background task manager for Flutter using platform-native APIs. Zero Flutter Engine overhead for I/O operations."
version: 1.0.3
homepage: https://github.com/brewkits/native_workmanager
repository: https://github.com/brewkits/native_workmanager
issue_tracker: https://github.com/brewkits/native_workmanager/issues

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  path_provider: ^2.1.0  # For integration and performance tests only

flutter:
  plugin:
    platforms:
      android:
        package: dev.brewkits.native_workmanager
        pluginClass: NativeWorkmanagerPlugin
      ios:
        pluginClass: NativeWorkmanagerPlugin
